name: mapbox_gl_dart
version: 0.2.1
description: Mapbox-gl wrapper for Dart. Library to use Mapbox GL JS in your web Dart projects.
homepage: https://github.com/andrea689/mapbox-gl-dart/
publish_to: none
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  js: ^0.7.1

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.10
